var textSet = {
    "chinese": {
        "Weak": "弱",
        "Strong": "强",
        "MorePopular": "受欢迎",
        "GraphTitle": "与关注用户观点差异平均值",
        "Reset": "重置",
        "Title": "回音演示",
        "Tolerance": "容忍度",
        "Never": "从不",
        "Sometimes": "偶尔",
        "PostMessage": "用户[t_node.name]发布了一条新消息。",
        "Default": "初始值",
        "GraphDiscription": "该图追踪了在整个网络中，主体与其关注用户之间观点差的平均值。该值的逐步减小显示了回音室效应的逐步产生。",
        "Low": "低",
        "ToleranceDiscription": "每条消息内在是带有观点的。我们把与当前主体观点相近的消息称为一致消息，否则为不一致消息。一致消息会影响当前主体的观点。同时，当前主体可能会取消关注发布不一致消息的已关注用户。",
        "ReadMessage": "用户[t_node.name]读了[concordant_nodes.length]条消息。",
        "Time": "时间",
        "UnfriendingDiscription": "该参数调节了当前主体取消关注的频率。每个主体可能会取关一位与其观点不一致的已关注用户，然后随机从社交网络中选取一个用户关注。",
        "Scenario04Discription": "如果主体会受到持有相似观点的关注用户影响并且能够改变其关注的用户，那么网络会很快地收敛成两个或以上的同质并且相互隔绝的回音室。回音室的数目取决于参数容忍度：抛开容忍度过高的情况不谈，更小的容忍度会产生更多的回音室。",
        "Medium": "中",
        "BecomeMoreProgressice": "用户[t_node.name]变得激进了。",
        "Stop": "停止",
        "Theme": "回音室在社交网络中是如何诞生的",
        "BecomeMoreConservative": "用户[t_node.name]变得保守了。",
        "Influence": "易影响度",
        "BecomeLessProgressice": "用户[t_node.name]变得不那么激进了。",
        "Language": "中文",
        "TranslatersName": "Chinese translation by <a href='http://roisevege.github.io/'>Wen Chen</a>",
        "High": "高",
        "Conservative": "保守",
        "ParameterSetting": "参数设置",
        "Scenario02Discription": "如果没有‘取消关注’机制，那么网络结构不会改变，并且每个主体都会一直置身于多样观点的环境中。然而，主体的观点仍然会受到其关注人的影响。依赖于不同的初始网络结构和主体的容忍度，社交网络会演变成 1）一个同质网络。换言之，近乎所有主体会持有一个相对中立的观点，或者 2）一个多种观点和谐共存的网络。",
        "Scenario03Discription": "如果所有主体皆不受他人影响，那么他们的观点也不会改变。然而，‘取消关注’机制仍然促使整个社交网络缓慢地分化为少量的同质子网络。",
        "AdvancedParameters": "重要参数",
        "InfluenceDiscription": "每个主体只接受与他观点相近的消息并且被其影响。每个主体的观点会逐渐演变并且趋近于他接受的消息的观点的平均值。该参数控制了主体观点趋同于其接受观点的速度。",
        "Speed": "速度",
        "Unfollow": "用户[t_node.name]取消关注了用户[del_node.name]，关注了用户[add_node.name]。",
        "Progressive": "激进",
        "Scenario": "场景",
        "Start": "开始",
        "Scenario01Discription": "如果所有主体不受他人影响并且从不改变其关注人，那么即使他们置身于一个观点多样的环境里，他们的观点也不会改变。另外，潜在的社交网络结构也不会改变。",
        "Often": "经常",
        "Scenario05Discription": "很高的容忍度会使取关机制近乎无用。人们轻易受到周围一切消息的影响，这促使整个系统很快收敛于一个统一的同质网络。",
        "RepostMessage": "用户[t_node.name]转发了用户[repost_node.name]的消息。",
        "Off": "关",
        "Unfriending": "取消关注",
        "BecomeLessConservative": "用户[t_node.name]变得不那么保守了。",
        "LessPopular": "不受欢迎"
    },
    "italiano": {
        "Weak": "Debole",
        "Strong": "Forte",
        "MorePopular": "Molto popolare",
        "GraphTitle": "Diversità media delle opinioni degli amici",
        "Reset": "Reset",
        "Title": "EchoDemo",
        "Tolerance": "Tolleranza",
        "Never": "Mai",
        "Sometimes": "A volte",
        "PostMessage": "L'utente [t_node.name] pubblica un nuovo messaggio.",
        "Default": "Predefinito",
        "GraphDiscription": "Questo grafico traccia come le opinioni degli amici di un agente diventano più o meno diversificate da quelle dell'agente. Una diversità decrescente indica la presenza dell'effetto di polarizzazione.",
        "Low": "Basso",
        "ToleranceDiscription": "I messaggi le cui opinioni cadono entro questo intervallo centrato sull'opinione dell'agente sono considerati concordanti, altrimenti sono discordanti. I messaggi concordanti influenzano l'opinione dell'agente. Inoltre, un agente può occasionalmente togliere l'amicizia a quei vicini che postano messaggi discordanti.",
        "ReadMessage": "L'utente [t_node.name] legge [concordant_nodes.length] messaggi.",
        "Time": "Tempo",
        "UnfriendingDiscription": "Questo parametro regola quanto spesso un agente toglierà l'amicizia a un vicino che posta messaggi discordanti, rimpiazzandolo con un vicino scelto a caso.",
        "Scenario04Discription": "Quando gli agenti sono influenzati dagli amici con opinioni affini e rompono l'amicizia con chi ha opinioni opposte, la rete sociale converge velocemente a due o più gruppi polarizzati (echo chambers). Per valori non troppo alti della tolleranza, il numero di gruppi dipende dalla tolleranza. Più bassa è la tolleranza, maggiore il numero di gruppi.",
        "Medium": "Medio",
        "BecomeMoreProgressice": "L'utente [t_node.name] diventa un po' più progressista.",
        "Stop": "Stop",
        "Theme": "Come si crea la polarizzazione sui social media",
        "BecomeMoreConservative": "L'utente [t_node.name] diventa un po' più conservatore.",
        "Influence": "Influenza",
        "BecomeLessProgressice": "L'utente [t_node.name] diventa un po' meno progressista.",
        "Language": "Italiano",
        "TranslatersName": "Traduzione italiana a cura di <a href='http://glciampaglia.com'>Giovanni Luca Ciampaglia</a> and <a href='http://cnets.indiana.edu/fil/'>Filippo Menczer</a>",
        "High": "Alto",
        "Conservative": "Conservatore",
        "ParameterSetting": "Impostazione dei parametri",
        "Scenario02Discription": "Senza la rottura delle amicizie, la struttura della rete sociale rimane immutata e gli agenti sono esposti a opinioni eterogenee. Tuttavia, l'influenza sociale porta gli agenti a cambiare opinione in base all'esposizione ad opinioni diverse. A seconda delle condizioni iniziali e della tolleranza, la rete o converge ad uno stato omogeneo in cui tutti (o quasi tutti) gli agenti hanno un'opinione moderata, oppure ad uno stato in cui due o più opinioni opposte coesistono.",
        "Scenario03Discription": "Senza influenza sociale, le opinioni non cambiano. Tuttavia, il processo di rottura delle amicizie permette agli agenti di riorganizzarsi lentamente in una manciata di gruppi omogenei.",
        "AdvancedParameters": "Parametri avanzati",
        "InfluenceDiscription": "L'opinione di un agente è aggiornata in modo tale da avvicinarsi alla media delle opinioni rispecchiate nei messaggi concordanti dei propri vicini. L'influenza controlla la velocità di tale processo.",
        "Speed": "Velocità",
        "Unfollow": "L'utente [t_node.name] smette di seguire l'utente [del_node.name], segue l'utente [add_node.name].",
        "Progressive": "Progressista",
        "Scenario": "Scenario",
        "Start": "Via",
        "Scenario01Discription": "Senza influenza sociale e rottura delle amicizie, gli agenti sono esposti a opinioni diversificate ma non cambiano la propria opinione, e la struttura della rete sociale sottostante rimane immutata.",
        "Often": "Spesso",
        "Scenario05Discription": "Con alta tolleranza, la rottura delle amicizie ha poco effetto. L'influenza sociale porta il sistema a convergere velocemente ad un singolo gruppo dalle opinioni omogenee.",
        "RepostMessage": "L'utente [t_node.name] ripubblica il messaggio dell'utente [repost_node.name].",
        "Off": "Spento",
        "Unfriending": "Rompere l'amicizia",
        "BecomeLessConservative": "L'utente [t_node.name] diventa un po' meno conservatore.",
        "LessPopular": "Poco popolare"
    },
    "english": {
        "Weak": "Weak",
        "Strong": "Strong",
        "MorePopular": "More Popular",
        "GraphTitle": "Average Diversity of Friend Opinions",
        "Reset": "Reset",
        "Title": "EchoDemo",
        "Tolerance": "Tolerance",
        "Never": "Never",
        "Sometimes": "Sometimes",
        "PostMessage": "User [t_node.name] posts a new message.",
        "Default": "Default",
        "GraphDiscription": "This plot tracks how the opinions of an agent’s friends become more or less different from the agent’s own opinion, on average. Decreasing diversity indicates an echo-chamber effect.",
        "Low": "Low",
        "ToleranceDiscription": "Tolerance defines how agents deal with different opinions. Messages reflecting opinions within this range from an agent’s own opinion are considered as concordant, otherwise as discordant. Concordant messages can influence an agent’s own opinion. Furthermore, an agent will occasionally unfriend neighbors who post discordant messages.",
        "ReadMessage": "User [t_node.name] reads [concordant_nodes.length] messages.",
        "Time": "Time",
        "UnfriendingDiscription": "This parameter regulates how often an agent will unfriend a neighbor who posts a discordant message, and replace it with a randomly selected new friend.",
        "Scenario04Discription": "When agents are influenced by their friends with similar opinions and can unfriend those with different opinions, the network quickly converges into two or more segregated and homogeneous echo-chambers. The number depends on the tolerance, as long as it is not too high: the smaller the tolerance, the more echo chambers.",
        "Medium": "Medium",
        "BecomeMoreProgressice": "User [t_node.name] becomes a bit more progressive.",
        "Stop": "Stop",
        "Theme": "How echo chambers emerge from social media",
        "BecomeMoreConservative": "User [t_node.name] becomes a bit more conservative.",
        "Influence": "Influence",
        "BecomeLessProgressice": "User [t_node.name] becomes a bit less progressive.",
        "Language": "English",
        "TranslatersName": " ",
        "High": "High",
        "Conservative": "Conservative",
        "ParameterSetting": "Parameter Setting",
        "Scenario02Discription": "Without unfriending, the network structure remains unchanged and agents are exposed to diverse opinions. However, influence causes agents’ opinions to change based on these exposures. Depending on the initial conditions and on the tolerance, the network converges either to a homogeneous state where all (or almost all) agents have a moderate opinion, or to a state where two (or more) diverse opinions coexist.",
        "Scenario03Discription": "Without influence, opinions do not change. However, the unfriending process allows the agents to slowly sort themselves into a few homogeneous groups.",
        "AdvancedParameters": "Advanced Parameters",
        "InfluenceDiscription": "An agent’s opinion is updated to become more similar, on average, to those reflected in concordant messages from neighbors. The influence controls how fast this happens.",
        "Speed": "Speed",
        "Unfollow": "User [t_node.name] unfollows user [del_node.name], follows user[add_node.name].",
        "Progressive": "Progressive",
        "Scenario": "Scenario",
        "Start": "Start",
        "Scenario01Discription": "Without influence and unfriending, agents are exposed to diverse opinions but their own opinions do not change, and the underlying network structure stays the same.",
        "Often": "Often",
        "Scenario05Discription": "With high tolerance, unfriending has small effect. Influence causes the system to quickly converge to a single group with homogeneous opinions.",
        "RepostMessage": "User [t_node.name] reposts user [repost_node.name]'s message.",
        "Off": "Off",
        "Unfriending": "Unfriending",
        "BecomeLessConservative": "User [t_node.name] becomes a bit less conservative.",
        "LessPopular": "Less Popular"
    },
    "japanese": {
        "Weak": "弱",
        "Strong": "強",
        "MorePopular": "人気がある",
        "GraphTitle": "友人の意見の平均多様性",
        "Reset": "初期化",
        "Title": "エコーデモ",
        "Tolerance": "許容範囲",
        "Never": "なし",
        "Sometimes": "時々",
        "PostMessage": "ユーザー[t_node.name]が新しいメッセージを投稿しました。",
        "Default": "初期値",
        "GraphDiscription": "このグラフは、友人たちの意見がどのように変化していくのかを表しています。時間と共に意見の多様性が減少するということは、エコーチェンバーの効果を示しています。",
        "Low": "低",
        "ToleranceDiscription": "各個人は自分の意見をもっていて、それをメッセージとして投稿します。友人のメッセージが自分の許容範囲にある場合は「合うメッセージ」、そうでない場合は「合わないメッセージ」とみなします。自分に合うメッセージから個人は影響を受けます。そして、自分に合わないメッセージを投稿する友人をしばしばアンフォローします。",
        "ReadMessage": "ユーザー[t_node.name]が[concordant_nodes.length]つのメッセージを読みました。",
        "Time": "時間",
        "UnfriendingDiscription": "このパラメータはアンフォローの頻度を表します。自分に合わないメッセージを投稿する友人1名をアンフォローし、その後、ランダムに新しい友人を1人フォローします。",
        "Scenario04Discription": "社会的影響とアンフォローがある場合、ネットワークは複数の同じ意見からなるエコーチェンバーに分断されます。許容範囲が大きすぎなければ、その大きさによって分断の数が決まります。許容範囲が小さいほど、多くのエコーチェンバーに分断されます。",
        "Medium": "中",
        "BecomeMoreProgressice": "ユーザー[t_node.name]はやや進歩的になりました。",
        "Stop": "停止",
        "Theme": "エコーチェンバーはどのようにしてソーシャルメディアから生じるのか",
        "BecomeMoreConservative": "ユーザー[t_node.name]はやや保守的になりました。",
        "Influence": "社会的影響",
        "BecomeLessProgressice": "ユーザー[t_node.name]はやや進歩的ではなくなりました。",
        "Language": "日本語",
        "TranslatersName": "Japanese translation by <a href='https://github.com/ayahito-saji'>Ayahito Saji</a> and <a href='http://www.colorlessgreen.info/'>Kazutoshi Sasahara</a>",
        "High": "高",
        "Conservative": "保守的",
        "ParameterSetting": "パラメータ設定",
        "Scenario02Discription": "アンフォローをなしにした場合、友人関係のネットワークは全く変わりませんが、個人はいろいろなメッセージを受け取ります。そして、受け取ったメッセージから社会的影響を受けて、個人の意見は徐々に変化していきます。初期状態と許容範囲の値によって、最終的には全員が中間的な1つの意見をもつネットワークか、2つ以上の違う意見が共存するネットワークのどちらかになります。",
        "Scenario03Discription": "社会的影響をなしにした場合、各個人の意見は変化しません。しかし、アンフォローを繰り返すことによって、徐々に同じ意見をもつ人からなる少数のグループをつくります。",
        "AdvancedParameters": "高度なパラメータ",
        "InfluenceDiscription": "各個人の意見は、その人に合うメッセージから影響を受けて変化し、次第に友人たちの意見に似ていきます。社会的影響のパラメータは、この変化の速さを調整します。",
        "Speed": "速度",
        "Unfollow": "ユーザー[t_node.name]がユーザー[del_node.name]をアンフォローし、ユーザー[add_node.name]をフォローしました。",
        "Progressive": "進歩的",
        "Scenario": "シナリオ",
        "Start": "開始",
        "Scenario01Discription": "社会的影響とアンフォローをなしにすると、個人はいろいろなメッセージを受け取りますが、自身の意見は変わりません。アンフォローもしないため、友人関係のネットワークも変化しません。",
        "Often": "しばしば",
        "Scenario05Discription": "許容範囲が大きい場合、アンフォローはあまり影響しません。この場合、社会的影響によって、すぐに全員が同じ意見をもつようになります。",
        "RepostMessage": "ユーザー[t_node.name]がユーザー[repost_node.name]のメッセージを共有しました。",
        "Off": "なし",
        "Unfriending": "アンフォローの頻度",
        "BecomeLessConservative": "ユーザー[t_node.name]はやや保守的ではなくなりました。",
        "LessPopular": "人気がない"
    }
}